Added remaining post related routes
Nsemble-Hope/Backend-API pull request #4
Opened 2021-05-01 10:35 UTC by AtharvaSune

Added the remaining post related routes, functionality is still not complete, have to add middleware capabilities.

2021-05-01 11:12 UTC, ameya0598 requested changes

2021-05-01 11:12 UTC, ameya0598 commented on src/routes/posts.js
> +    let newComment = {
Can we add time and date to the comment as well?
What about the upvotes and downvotes?

2021-05-01 11:22 UTC, AtharvaSune commented on src/routes/posts.js
> +    let newComment = {
Date is set to Date.now() as default value, I will add upvotes, downvotes to the comment sub doc :+1:

2021-05-01 11:26 UTC, AtharvaSune commented
Added upvotes and downvotes to post model, and set default value to 0

2021-05-02 09:45 UTC, ameya0598 commented
One more thing, we should also add a field which says *reacted?* to make sure that one person is allowed to upvote or downvote only once.

2021-05-02 10:42 UTC, AtharvaSune commented
> One more thing, we should also add a field which says _reacted?_ to make sure that one person is allowed to upvote or downvote only once.

Right, so for that does this method seem like a good idea,  for posts we maintain a reacted array , Which consists list of people who have reacted to the post (list of `unique identifier`)

2021-05-02 11:27 UTC, ameya0598 commented
> > One more thing, we should also add a field which says _reacted?_ to make sure that one person is allowed to upvote or downvote only once.
> 
> Right, so for that does this method seem like a good idea, for posts we maintain a reacted array , Which consists list of people who have reacted to the post (list of `unique identifier`)

Yes

2021-05-02 11:41 UTC, AtharvaSune commented
For now we'll just maintain who have reacted, once that functionality is tested, we can test more features like type od react and stuff like that
@ameya0598

2021-05-02 11:48 UTC, ameya0598 approved these changes

2021-05-03 16:18 UTC, merged